### ISSUE TITLE
Separation of "summary" and "foreword"

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/metanorma-unece#7]
"Foreword" and "Summary" are two different concepts. And we should implement them separately.

i.e. in Rec 42, this is wrong, only `.Foreword` should be used:
```adoc
[abstract]
.Foreword
It is my pleasure to introduce this new recommendation on monitoring the effectiveness of policies and procedures that facilitate trade and speed up international supply and value chains. Facilitating trade is one of the vectors to improving peoples’ lives and reducing inequalities. Using international standards and standard procedures creates a level playing field for all actors in both developed and developing economies.
```

**Comment by opoudjis** [comment]
You mean, it's wrong it's wrong in the plenary.

If anything is wrong, it's using the Asciidoctor Abstract as a Foreword instead of Summary. However, I am unwilling to change all of the Metanorma stack for this standard, which has very little to do with Metanorma to begin with. This means that Summary will need to be added as a separate prefatory section.

**Comment by ronaldtse** [comment]
> This means that Summary will need to be added as a separate prefatory section.

It's not only this document, but also in RFCs there's also the concept of an "abstract". An "abstract" is not a "Foreword" in any case.

**Comment by opoudjis** [comment]
Separating in clause_parse: sections styled as `[abstract]` in metanorma-unece will now be extracted as a separate `abstract` element, and moved to the start of the preface.
